name: find-clang
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm --needed git ninja cmake yasm nasm unzip p7zip python-pip python-cairo curl jq wget
          pip3 install -U --break-system-packages setuptools rst2pdf mako jsonschema meson         
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
      
      - uses: actions/checkout@main
      - name: Checkout toolchain
        uses: actions/checkout@main
        with:
          repository: shinchiro/mpv-winbuild-cmake
          ref: clang
          path: mpv-winbuild-cmake

      - name: Loading build64 cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/mpv-winbuild-cmake/build64
          key: build64-${{ github.run_id }}
          restore-keys: |
            build64

      - name: Finding clang
        run: |
          find . -name "clang++"
          find . -name "llvm-objcopy"
          find . -name "x86_64-w64-mingw32-ld"
            
      - name: Packaging gcc toolchain
        run: |
          7z a clang.7z mpv-winbuild-cmake/build64/*
          
      - name: Release
        continue-on-error: true
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ env.short_time }}
          name: ${{ env.short_time }}
          files: clang.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
