name: release
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
  
jobs:
  release:
    name: Building gcc
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:    
      - name: Install Dependencies
        run: |
          sudo echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm --needed git gyp mercurial subversion ninja cmake ragel yasm nasm asciidoc enca gperf unzip p7zip xz gcc-multilib clang python-pip curl jq lib32-glib2 wget
          pip3 install -U setuptools rst2pdf mako jsonschema meson
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD
      
      - uses: actions/checkout@main
      
      - name: Loading build64 cache
        uses: actions/cache@main
        id: build64
        with:
          path: build64
          key: build64
          
      - name: Loading repository cache
        uses: actions/cache@main
        id: src_packages
        with:
          path: src_packages
          key: src_packages
          
      - name: Get current time
        run: |
          echo "short_time=$(date "+%Y-%m-%d")" >> $GITHUB_ENV          
      - name: Packaging mpv
        run: |
          mkdir release64
          curl -OL https://github.com/eko5624/mpv-config/archive/refs/heads/main.zip
          unzip main.zip
          mv mpv-config-main/portable_config release64
          find build64 -name "mpv.exe" -print0 | xargs -0 -I {} cp {} release64
          find build64 -name "mpv.exe" -print0 | xargs -0 -I {} ls {}
          7z a mpv-${{ env.short_time }}.7z release64/*
          7z a build64-dir.7z build64/*
          7z a src_packages-dir.7z src_packages/*
          
      - name: Release build64
        continue-on-error: true
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ env.short_time }}
          name: ${{ env.short_time }}
          files: |
            mpv*.7z
            build64-dir.7z
            src_packages-dir.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
